name: Deneme


on:
    workflow_dispatch:
        defaults:
            run:
                shell: bash


jobs:
  deneme1:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install dependiencies
        - run: apt-get install git build-essential pkg-config libtool automake automake autopoint gettext && apt-get build-dep vlc
        - name: Clone VLC
        - run: git clone https://github.com/bahadir200-cloud/vlc && cd vlc && ./bootstrap
        - name: Configure
        - run: ./Configure
        - name: Build IT!
        - run: make
        - name: Install
        - run: make install
        - name: Clean
        - run: make clean

