name: Deneme


on:
    workflow_dispatch


jobs:
  deneme1:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install dependiencies
          run: ls && sudo apt-get install git build-essential pkg-config libtool automake automake autopoint gettext && sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list && sudo apt-get update && sudo apt-get build-dep vlc
        - name: Clone VLC
          run: git clone git://git.videolan.org/vlc.git && cd vlc && ./bootstrap
        - name: Configure
          run: ls && ls vlc/ && ./configure
        - name: Build IT!
          run: make
        - name: Install
          run: sudo make install
        - name: Clean
          run: make clean

